image: node:lts

stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install

test:
  stage: test
  needs: []
  script: make lint_rest

test:lint:
  stage: test
  needs: [setup]
  script: npx eslint

# same version for files and valid json
test:py:
  image: python:slim
  stage: test
  needs: []
  script:
    - python -m json.tool addon/manifest.json > /dev/null
    - python -m json.tool addon/preset.json > /dev/null
    - python -m json.tool addon/schema.json > /dev/null
    - python meta/same_version.py
  before_script:
    - ''
