image: node:lts

stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install

test:
  stage: test
  needs: []
  script: make test

test:lint:
  stage: test
  needs: [setup]
  script: npx eslint

test:version:
  image: python:slim
  stage: test
  needs: []
  script: ./meta/same_version.py
